export const MEDIA_QUERIES_POINTS = {
  mobileMinimum: "max-width: 375px",
  mobileSmall: "max-width: 640px",
  mobileSmallExtra: "max-width: 430px",
  mobile: "max-width: 767px",
  mobileAbove: "min-width: 768px",
  tabletMinimum: "max-width: 768px",
  tabletSmall: "max-width: 920px",
  tabletMedium: "max-width: 1024px",
  tablet: "max-width: 1280px",
  tabletAbove: "min-width: 1281px",
  desktopMinimum: "max-width: 1320px",
  desktopSmall: "max-width: 1366px",
  desktopAboveSmall: "min-width: 1367px",
  desktopMedium: "max-width: 1480px",
  desktopAboveMedium: "min-width: 1481px",
  desktopLarge: "max-width: 1820px",
  desktopAboveLarge: "min-width: 1821px",
  desktop: "max-width: 1920px",
  desktopAbove: "min-width: 1921px",
};
